version: '3'
services:
  bsc-node:
    image: ghcr.io/bnb-chain/bsc:latest 
    container_name: bsc
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - .data/bsc/root/.bsc:/root/.bsc
    networks:
      - bsc-network
    environment:
      - NETWORK_ID=97 # ID for BSC Testnet
      - RPC_PORT=8545
      - WS_PORT=8546
    command:
      - --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --networkid ${NETWORK_ID}

  hardhat:
    image: ethereumoptimism/hardhat:latest
    container_name: hardhat
    working_dir: /project
    volumes:
      - ./.data/hardhat/project:/project
    networks:
      - bsc-network
    tty: true
    environment:
      - NODE_ENV=development
      - BSC_RPC_URL=http://bsc-node:8545
    depends_on:
      - bsc-node

networks:
  bsc-network:
    driver: bridge

